### ISSUE TITLE
confused about the function "computeCatR"

### ISSUE THREAD

**Issue by qyx1121** [facebookresearch/reliable_vqa#3]
Hi, I'm confused about this code:

```
def computeCatR(self, evalQA, risk_tolerance, best=False):
       total_questions = len(evalQA)
       _, rc_data = zip(*evalQA.items())
       index = total_questions
       while index > 0 and rc_data[index - 1]["risk"] > risk_tolerance:
               index -= 1
       index -= 1

        if (
            -1 < index < (total_questions - 1)
            and rc_data[index]["confidence"] == rc_data[index + 1]["confidence"]
        ):
            while index > -1 and (
                rc_data[index]["confidence"] == rc_data[index + 1]["confidence"]
                or rc_data[index]["risk"] > risk_tolerance
            ):
                index -= 1

        cov = rc_data[index]["coverage"] if index > -1 else 0.0
```

If any part of rc_data has the same "confidence" starting with index=0, then after the second while loop, the index will be -1, and cov will always be 0.

**Comment by qyx1121** [comment]
Please tell me how to solve this problem, thanks!

**Comment by SpencerWhitehead** [comment]
Hello, thanks for your interest!

This is intentional and I believe should be correct: Coverage at risk is the maximum coverage a model could obtain while having at most `risk_tolerance` risk on the answered questions. If you have the same confidence values at indices `i` and `i+1` but `risk[i] <= risk_tolerance` and `risk[i + 1] > risk_tolerance` (which would be the case after the first loop), then we cannot use `i` as our stopping point because the same confidence can have risk > `risk_tolerance` (i.e., we couldn't use `confidence[i]` as a threshold and strictly have risk <= `risk_tolerance`). Therefore, if they have the same confidence values, then we find the next index that has a different confidence value and has risk below `risk_tolerance` (the second loop).

**Comment by qyx1121** [comment]
I see, thx for your reply~
